<?php

namespace Diego\DemoBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends EntityRepository
{

    public function findAllMayorPrecio($p) {
        
        /* USANDO DQL */
        $query = $this->getEntityManager()->createQuery(
            "SELECT p
            FROM DiegoDemoBundle:Product p
            WHERE p.price >= :price
            ORDER BY p.price ASC"
        )->setParameter('price', $p);    


        return $query->getResult(); 
    }

    public function findOneByIdJoinedToCategory($id)
    {
        $query = $this->getEntityManager()
            ->createQuery(
                'SELECT p, c FROM DiegoDemoBundle:Product p
                LEFT JOIN p.category c
                WHERE p.id = :id'
            )->setParameter('id', $id);

        //try {
            return $query->getSingleResult();
        // } catch (\Doctrine\ORM\NoResultException $e) {
        //     throw new \Exception(
        //         'No product found for id '.$id
        //     );
        // }
    }
}
